### PR TITLE
Fix axis facets

### LINKED ISSUE #1720: ggplotly breaks discrete x-axis with facet_yyyy in panels > 1 with only one category
ggplotly breaks a discrete axis with` facet_yyyy` when there is only one category present in a  panel, except for the case that this happens to be the first panel. I stumbled over this bug based on a question on [Stackoverflow](https://stackoverflow.com/questions/60606101/x-axis-error-with-ggplotly-and-facet-wrap#comment107224862_60606101):
``` r
library(plotly)

d <- data.frame(cat = c("A", "A", "A"), pan = paste("Panel", c(1, 2, 2)))
ggplot(d, aes(cat)) +
  geom_bar() +
  facet_wrap(~pan)
```

```
ggplotly()
```

facet-breaks-axis

<sup>Created on 2020-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by trekonom**
This PR fixes a bug in `verify_attr` which closes #1720 and #1577 .

Adding the fix the reprex from #1720 is rendered like so

grafik

and the reprex from #1577 like so:

grafik

### CODE REVIEW

File: tests/testthat/test-facet-axis.R [hunk 1]
```diff
@@ -0,0 +1,11 @@
+test_that("ggplotly does not break discrete x-axis with facet_yyyy in panels > 1 with only one category", {
+  d <- data.frame(cat = c("A", "A", "A"), pan = paste("Panel", c(1, 2, 2)))
+  gp <- ggplot(d, aes(cat)) +
+    geom_bar() +
+    facet_wrap(~pan)
+  L <- plotly_build(ggplotly(gp))
+  # tickvals, ticktext and categoryarray have class 'AsIs'
+  expect_equal(class(L$x$layout$xaxis2$tickvals), "AsIs")
+  expect_equal(class(L$x$layout$xaxis2$ticktext), "AsIs")
+  expect_equal(class(L$x$layout$xaxis2$categoryarray), "AsIs")
```
Comment (cpsievert) [inline tests/testthat/test-facet-axis.R:10]:
```suggestion
  lapply(L$x$layout[c("xaxis", "xaxis2")], function(axis) {
    expect_s3_class(axis$tickvals, "AsIs")
    expect_s3_class(axis$ticktext, "AsIs")
    expect_true(axis$ticktext == "A")
    expect_s3_class(axis$categoryarray, "AsIs")
    expect_true(axis$categoryarray == "A")
  })
```

**Comment by cpsievert** [comment]
Looks great, thank you! If you agree with the suggested change, please commit it and add a news item, then I'll merge

BTW, have you tried to create and/or [run visual tests](https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md#running-visual-tests-via-docker)? I think we can get away with not having one here, but it'd be great to have them in some of your other PRs

**Comment by trekonom** [comment]
Just commited your changes and added a news item.

Regarding the visual tests:

- Visual tests and svgs are already present for PRs #1779 and #1782 .  
- However the visual tests always failed while vdiffr::manage_cases showed successful doppelganger.
- Therefore I decided to comment them out in my commits.

I also tried running the visual tests via docker ... 

- Following your instructions , i.e. running `docker run -v $(pwd):/home/plotly --privileged -p 3838:3838 cpsievert/plotly-orca` always resulted in the error `invalid reference format`.
- But as I used docker for the first time maybe I simply got something wrong.

**Comment by cpsievert** [comment]
Hmm, are you in windows powershell? https://stackoverflow.com/a/51379726/1583084

**Comment by trekonom** [comment]
(: Thanks a lot. It was the Powershell issue. Now the docker works like a charm. BTW: I also figured out my issue with visual testing inside RStudio. After running the tests via `devtools::test() `(as you suggested in the contributing guidelines) instead of pressing the "Run Tests" button my visual tests passed.

**Comment by cpsievert** [comment]
Ahh, yea, sorry, I should've mentioned before that the visual tests should only really only be run via docker
